title Arch Linux (clearcpuid=514)
linux /vmlinuz-linux
initrd /amd-ucode.img
initrd /initramfs-linux-fallback.img
options root="LABEL=ROOT" rw quiet clearcpuid=514 loglevel=3 systemd.show_status=auto rd.udev.log_level=3