#!/bin/sh
window=$(swaymsg -t get_tree | jq -r '..|try select(.app_id == "'Alacritty'")|try select(.name == "'dropdownterminal'")')
windowpid=$(echo $window | jq -r '.pid')

if [ ! -z "$windowpid" ]; then
	if [ "$(echo $window | jq -r .visible)" = "true" ]; then
		swaymsg [ app_id="Alacritty" pid="$windowpid" ] move scratchpad
	else
		swaymsg [title="dropdownterminal" app_id="Alacritty"] move container to workspace current, move position cursor, focus
	fi
else
	swaymsg exec 'alacritty -o window.opacity=0.8 -T "dropdownterminal"'
fi
