# mimi config file
# https://github.com/BachoSeven/mimi

# Defaults
TERM: foot
MENU: fuzzel
MENUARGS: --dmenu

# Basic
text/plain: autotermrun $EDITOR
inode/directory: autotermrun lf
application/json: autotermrun $EDITOR

# Media
audio/: mpv
video/: mpv
image/: imv

# Docs
pdf: zathura

# Web Browser
text/html: firefox
text/xml: firefox
application/xhtml_xml: firefox
x-scheme-handler/http: firefox
x-scheme-handler/https: firefox
x-scheme-handler/ftp: firefox
x-scheme-handler/about = firefox
x-scheme-handler/unknown = firefox

# Font
ttf: imvFontPreview
otf: imvFontPreview
