hwdec=vaapi
gpu-context=wayland
vaapi-device=/dev/dri/renderD128

ao=pipewire
alang=eng
slang=eng
sub-auto=fuzzy
keep-open=yes
force-window=immediate

screenshot-template="%F - [%P]v%#01n"
screenshot-format=png
screenshot-directory=/home/vbt/.xdgpath/pictures

osc=no
ytdl-raw-options=sub-lang=en,write-auto-sub=
ytdl-format=bestvideo[vcodec^=av01][height<=720]+bestaudio
cache=yes