#!/bin/sh -eu
# https://git.sr.ht/~emersion/dotfiles/tree/master/item/bin/wl-copy-file

path="$(realpath "$1")"

if ! [ -e "$path" ]; then
	echo >&2 "No such file or directory"
	exit 1
fi

exec wl-copy -t "text/uri-list" "file://$path"
