[theme]
theme = "native"
[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:80) |"
short = " $title.str(max_w:50) |"

[[block]]
block = "music"
format = "{$combo.str(max_w:25,rot_interval:0.5) { $play|}|}"

[[block]]
block = "custom"
command = "echo "
interval = "once"
[[block.click]]
cmd = "killall wlsunset || wlsunset -T 4001"
button = "left"

[[block]]
block = "net"
format = " $icon{$signal_strength $ssid $frequency|} $device"
[[block.click]]
button = "left"
cmd = "iwgtk"
[[block.click]]
button = "right"
cmd = "blueman-manager"

[[block]]
block = "keyboard_layout"
driver = "sway"
[block.mappings]
"English (Dvorak)" = "dv"
"English (US)" = "qw"
[[block.click]]
button = "left"
cmd = "swaymsg mode keyboard"
[[block.click]]
button = "right"
cmd = "swaymsg mode keyboard"


#[[block]]
#block = "battery"
#format = " $icon $percentage "


[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:'%I:%M %p %a %d-%m-%Y')"

[[block]]
block = "sound"
driver = "pulseaudio"
format = " $icon{ $volume|} "
[[block.click]]
button = "left"
cmd = "pavucontrol-qt"

[[block]]
block = "menu"
text = "\uf011"
[[block.items]]
display = " -&gt; Power Off &lt;-"
cmd = "sudo poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = " -&gt;  Reboot   &lt;-"
cmd = "sudo reboot"
confirm_msg = "Are you sure you want to reboot?"

[[block]]
block = "privacy"
[[block.driver]]
name = "v4l"
[[block.driver]]
name = "pipewire"
